# https://hub.docker.com/r/ashleykza/stable-diffusion-webui
# https://github.com/ashleykleynhans/stable-diffusion-docker#running-locally
version: '3.9'
services:
  web:
    image: ashleykza/stable-diffusion-webui
    container_name: stable-diffusion-webui
    ports:
      - 3000:3001
      - 3010:3011
      - 3020:3021
      - 6006:6066
      - 8888:8888
    environment:
      JUPYTER_PASSWORD: 'Jup1t3R!'
      ENABLE_TENSORBOARD: 1
      #DISPLAY: ':99'
      #DISABLE_AUTOLAUNCH: 1
    volumes:
      - type: bind
        source: './dataset'
        target: '/dataset'
    working_dir: '/workspace'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
